/**
 * Core domain types for the SoFi Stadium Operations Copilot.
 * All types are plain data (no classes) — safe to serialize to JSON.
 *
 * Priority convention: 1 = highest urgency (lower number = more urgent).
 */

// ---------------------------------------------------------------------------
// Venue / Zone
// ---------------------------------------------------------------------------

export type ZoneType =
  | 'gate'
  | 'section'
  | 'concourse'
  | 'medical'
  | 'restroom'
  | 'food'
  | 'accessibility';

export interface Coordinates {
  x: number;
  y: number;
}

export interface Zone {
  zoneId: string;
  name: string;
  type: ZoneType;
  capacity: number;
  /** Current simulated occupancy count (not percentage). */
  currentOccupancy: number;
  /** Zone IDs reachable via step-free (accessible) paths. */
  accessibleRoutes: string[];
  adjacentZones: string[];
  coordinates: Coordinates;
}

export interface VenueConfig {
  venueId: string;
  venueName: string;
  city: string;
  capacity: number;
  zones: Zone[];
}

// ---------------------------------------------------------------------------
// Live Signals
// ---------------------------------------------------------------------------

export type WeatherCondition = 'clear' | 'rain' | 'heavy-rain' | 'heat-alert';

export interface ZoneOccupancySignal {
  zoneId: string;
  /** 0–100 as a percentage of capacity. */
  occupancy: number;
  trend: 'rising' | 'stable' | 'falling';
  updatedAt: string; // ISO 8601
}

export interface GateDelaySignal {
  gateId: string;
  delayMinutes: number;
  cause: 'security' | 'capacity' | 'incident';
  /** Estimated number of fans currently queued at this gate. */
  fanQueueCount: number;
  updatedAt: string;
}

export interface WeatherSignal {
  condition: WeatherCondition;
  /** Multiplier applied to concourse occupancy (1.0–2.0; rain pushes fans inside). */
  concourseMultiplier: number;
  updatedAt: string;
}

export type NeedType = 'wheelchair' | 'visual' | 'hearing' | 'elderly' | 'cognitive';

export interface EscortRequest {
  requestId: string;
  /** Anonymised fan identifier (session-scoped). */
  fanId: string;
  currentZone: string;
  destinationZone: string;
  needType: NeedType;
  status: 'pending' | 'assigned' | 'in-progress' | 'completed';
  assignedVolunteerId?: string;
  requestedAt: string;
  /** Computed at task generation time for priority calculation. */
  waitingMinutes: number;
}

export type IncidentSeverity = 'low' | 'medium' | 'high';
export type IncidentType = 'medical' | 'security' | 'facilities' | 'crowd';

export interface IncidentReport {
  incidentId: string;
  type: IncidentType;
  zone: string;
  severity: IncidentSeverity;
  status: 'open' | 'responding' | 'resolved';
  reportedAt: string;
}

// ---------------------------------------------------------------------------
// Rules Engine Output
// ---------------------------------------------------------------------------

export type ZoneStatusLevel = 'comfortable' | 'busy' | 'critical';

export interface ZoneStatus {
  zoneId: string;
  status: ZoneStatusLevel;
  /** Raw occupancy percentage (0–100). */
  occupancyPct: number;
  /** After applying weatherSignal.concourseMultiplier. */
  weatherAdjustedPct: number;
}

export type TaskType =
  | 'crowd-reroute'
  | 'escort'
  | 'gate-rebalance'
  | 'medical-response'
  | 'security-response'
  | 'facilities';

export type TaskStatus = 'open' | 'assigned' | 'in-progress' | 'resolved';

export interface Task {
  taskId: string;
  /** Lower number = higher urgency. 1 = most urgent. */
  priority: number;
  type: TaskType;
  /** Human-readable zone name. */
  location: string;
  zoneId: string;
  /** One-line deterministic explanation generated by the rule that created this task. */
  reasoning: string;
  status: TaskStatus;
  assignedTo?: string;
  /** IDs of tasks that conflict with this one. */
  conflicts: string[];
  createdAt: string;
  /** Source signal metadata (used for Gemini explanation grounding). */
  metadata?: Record<string, unknown>;
}

export type ConflictType = 'same-volunteer' | 'route-collision' | 'competing-reroute';

export interface ConflictFlag {
  conflictId: string;
  taskA: string;
  taskB: string;
  conflictType: ConflictType;
  resolution?: string;
}

// ---------------------------------------------------------------------------
// Volunteer
// ---------------------------------------------------------------------------

export interface Volunteer {
  volunteerId: string;
  name: string;
  currentZone: string;
  status: 'available' | 'busy' | 'off-duty';
  assignedTaskId?: string;
}

// ---------------------------------------------------------------------------
// Simulation State
// ---------------------------------------------------------------------------

export interface SimulationState {
  venueId: string;
  tick: number;
  timestamp: string;
  occupancySignals: ZoneOccupancySignal[];
  gateDelaySignals: GateDelaySignal[];
  weatherSignal: WeatherSignal;
  escortRequests: EscortRequest[];
  incidents: IncidentReport[];
  volunteers: Volunteer[];
}

// ---------------------------------------------------------------------------
// Rules Engine Input (convenience bundle)
// ---------------------------------------------------------------------------

export interface RulesEngineInput {
  venue: VenueConfig;
  state: SimulationState;
}

export interface RulesEngineOutput {
  zoneStatuses: ZoneStatus[];
  tasks: Task[];
  conflicts: ConflictFlag[];
}
